README.md

From his README: "From 14th of February 2017 it's renamed from lablqt to lablqml because it is actually about QtQuick and not QtWidgets or Qt itself."

Autor changed project name 

---

README.md

I wrote an OCaml rule extension to [Bazel](https://bazel.build), Google's open source build tool, at https://github.com/jin/rules_ocaml.

Added Bazel to build tools

---

README.md

Added link to the Obandit multi-armed bandit library under the "Science" section.

Added link to the Obandit multi-armed bandit library

---

README.md

From the Sklml web site:
> Sklml, the OCaml parallel skeleton system, is a functional parallel skeleton compiler and programming system for OCaml programs.
> 
> Writing parallel programs is not easy, and debugging them is usually a nightmare. To cope with these difficulties, the skeleton programming approach uses a set of predefined patterns for parallel computations. The skeletons are higher order functional templates that describe the program underlying parallelism.
> 
> Sklml is a new framework for parallel programming that embeds an innovative compositional skeleton algebra into the OCaml language. Thanks to its skeleton algebra, Sklml provides two evaluation regimes to programs: a regular sequential evaluation (merely used for prototyping and debugging) and a parallel evaluation …

Parallelism : Sklml

---

README.md

Ocp-index-top implements a toplevel directive `#doc` that can be used to lookup documentation using ocp-index's LibIndex module.
It is written by myself. It's a bit of a hack, and there's an issue with utop since utop 2.0.1 (see https://github.com/reynir/ocp-index-top/issues/9). Because of the issues it's perhaps not 'awesome' enough, but I find it quite useful myself when exploring things in the toplevel.

Add ocp-index-top

---

sotu.md

Removes OcamlScript since it's just the old name of BuckleScript. Also fixed the capitalization of BuckleScript

Remove OcamlScript

---

README.md

I added it next to tuareg to keep the emacs packages close to each other.

Add merlin-eldoc

---

README.md

- Add link to Caqti repository
- Add link to how-to article using Caqti and Postgre-SQL

Add Caqti (database abstraction layer)

---

README.md

Whilst @samoht is maintaining Alcotest, the upstream repo has more
recent commits and has some stars, so it looks canonical to me.

Use the upstream URL for the alcotest repository

---

.travis.yml

Fixes #73. Travis will need to be enabled on https://travis-ci.com/ (or https://travis-ci.org/; not sure how the migration works) before builds will start.

Enable awesome_bot on Travis builds

---

README.md

This is pretty well working ocaml debugger for vscode. And as far as I know the only debugger for vscode as well.

Add OCaml Debugger / ocamlearlybird to the list

---

README.md

Async now has its own dedicated page.

README: Link async to its own page

---

README.md

After a discussion in https://github.com/ocaml-community/awesome-ocaml/pull/173 it makes sense to provide the link to the PyTorch bindings themselves too.

Add PyTorch bindings

---

README.md

If you visit the old one at https://github.com/aryx/pfff you can see it has the message in the description that development had been moved to https://github.com/returntocorp/pfff

Fix pfff repository URL.

---

README.md

Caramel is currently compiling a subset of OCaml syntax to Erlang source code

Add Caramel to Languages and Compilers

---

README.md

Adding an app to learn and execute OCaml code directly on iPhone/iPad/Mac.

Adding 'OCaml: Learn & Code'

---

README.md

Goes without saying that https://github.com/ocaml/ocaml-lsp should be here.

Add ocaml-lsp in Editors section.

---

README.md

Hi!
I sometimes write stuff™ on my blog and sometimes it is about OCaml. I wouldn’t call these articles rocket science but still, they might be interested for the typical audience of this awesome list.
No hard feelings if you’d rather not add it! I would totally understand.

Add a link to lthms’s blogposts about OCaml

---

README.md

Hello!
I would like to add library that i recently published on opam. It is a PPX deriver that generates function for validating given type based on attributes.
Here is example usage 
```ocaml
type test_record = {
min : string; [@min_length 2]
max : string; [@max_length 5]
numeric_list : (int [@less_than 10]) list; [@min_length 2] 
}
[@@deriving validate]
let example_record = { min = "ab"; max = "hello"; numeric_list = [1, 2, 3] }
let validation_result = validate_test_record example_record
```
Repo: https://github.com/Axot017/validate

Add `validate`

---

README.md

Darklang ditched OCaml years ago. See:
- https://blog.darklang.com/leaving-ocaml/
- https://github.com/darklang/dark
It's all in F# now. Big bummer

Remove "Dark" from large source code examples

---

README.md

[Mazeppa](https://github.com/mazeppa-dev/mazeppa) is a modern supercompiler for call-by-value functional languages that subsumes both deforestation and partial evaluation.

docs(README): add `mazeppa`, a modern supercompiler
