README.md
See https://github.com/janestreet/rpc_parallel
=> Async_parallel is deprecated in favour of rpc_parallel

README.md
Add "Introduction to Functional Programming in OCaml" to the list of online courses.
=> Add link to online course.

README.md
=> Added Lambda Soup.

README.md
Not sure if this belongs in Web or Serialization, but I added it to Web because the HTML5 parser is the main contribution.
=> Added Markup.ml.

README.md
It's a logger implemented in OCaml for Fluentd (http://www.fluentd.org/).
=> Add fluent-logger (https://github.com/fluent/fluent-logger-ocaml)

README.md
=> Various resources

README.md
https://github.com/aantron/namespaces
I am not sure where this belongs – packaging, or developer tools? I chose packaging for the PR.
=> Add Namespaces.

README.md
I've added a few links of projects that I found over the last couple of month on Reddit/OCaml and elsewhere.
=> Some new links 

README.md
=> add gen_js_api

README.md
This article explains how to use bindings OCaml to Cordova plugins.
=> Add an article about Cordova and OCaml to develop mobile applications

README.md
Added commonjs_of_ocaml because I want to help people with my work/am terribly vain.
=> Added commonjs_of_ocaml

README.md
=> +decompress

README.md
added vscode-ocaml as a suggestion for Editor Plugins
=> added vscode-ocaml

README.md
Compile and execute OCaml code online.
=> added codingground

README.md
I tried to use the wording from https://www.reddit.com/r/ocaml/comments/532ip2/github_janestreetbase_standard_library_for_ocaml/d7q453a/
=> Add core_kernel and base

README.md
I ran across this neat-o example project by @smolkaj, so I wanted to add it (and the resources it refers to) to the list! `(=`
=> Add more parsing resources (Sedlex, Obelisk, etc.)

README.md
=> fixed Mongo.ml link

README.md
Add link to OCamlverse! 😃 
CC @Bluddy
=> Add link to OCamlverse

README.md
I did not exhaustively fix all of the issues; this was just a quick run-through.
=> README: Fix some of the awesome_bot link issues

README.md
https://github.com/rizo/awesome-ocaml/pull/145#issuecomment-420577417
CC @gasche. Should I add any other tools?
=> Add benchmarking tools

README.md
I added two "specific" compilers to the list !
=> Added MirageOS and OMIcroB to the list

README.md
Add [esy](https://github.com/esy/esy) to Distribution section
=> Add esy to Distribution section

README.md
Facebook abandoned the tool but it has new maintainer
=> pfff is now moved to a new place

README.md
Add https://github.com/arenadotio/pgx to the list of bindings
=> Add pgx, a pure OCaml Postgres client library

README.md
* CBOR encoder/decoder by @ygrek.
* expect-test test framework by @janestreet.
=> Add 2 more awesome OCaml projects

README.md
=> Update ocaml-cordova link

README.md
L332: https://www.seas.upenn.edu/~cis120/current/programming_style.shtml -> https://www.seas.upenn.edu/~cis120/20fa/ocaml_style/
L333: https://bitbucket.org/camlspotter/compiler-libs-hack -> https://camlspotter.blogspot.com/2012/09/a-safe-but-strange-way-of-modifying.html
=> fix outdated link

README.md
Updated version of PR: "Add book: Programming Language Examples Alike Cookbook" #160 
@cwfoo Is the suggestion in the original PR and this update okay with you? If so, let's close the other PR and merge this one. If not, I can close this PR and the discussion can continue in the original PR
=> Add Programming Language Examples Alike Cookbook

README.md
Typo: funcitons => funcitons in README.md
=> Typo: funcitons => funcitons in README.md

README.md
Add some new libraries like piaf, remove old archived repos and dead links.
=> Update some ecosystem tools/libraries

README.md
bistro is the (not so) new name of guizmin (I'm the author)
=> update info on bistro

README.md
Add atdgen among serialization.
=> Update README.md - Add Atdgen among serialization

README.md
**Functional Programming in OCaml** is the past title of **OCaml Programming: Correct + Efficient + Beautiful**
=> Update the book name as it is now

README.md
Add a videos section with Dr. Michael R. Clarkson's OCaml video list
=> Add a videos section with Dr. Michael R. Clarkson's OCaml video list

README.md
=> Mention opam-switch-mode

README.md
Cc @gasche @yurug feel free to proofread this small PR
=> Fix OCaml-MOOC URL & Add OCaml-MOOC YouTube URL

README.md
Adding a new library in the machine learning space. This library implements a Fully-Connected Neural Network using purely functional programming in OCaml. Provides lots of customizing functions such as loss functions, optimizers, and gradient descent methods. 
Train and run a neural network on any dataset. We implement a fully-connected multi-layered neural network that learns network parameters using back propagation implemented as a gradient descent algorithm. The data structure we use is OCaml Arrays. We further provide the following hyper-parameter customizability:
- Optimization Functions:  `Vanilla GD | GD w/Momentum | RMS Prop` <br>
- Activation Functions:  `ReLU | TanH | Sigmoid ` <br>
- Gradient Descent Type:  `Stochastic GD | Mini-Batch GD | Vanilla GD` <br>
- Learning Rate: …
=> Add `ocaml-nn` to the Machine Learning libraries section

README.md
=> Add sqids-ocaml

README.md
Just FYI @yurug @AltGr @gasche @brabalan
=> Mention the learn-ocaml project

README.md
I’m getting paid for working on Tezos, so feel free to close this PR if you believe there is a conflict of interest of sort, but arguably, Tezos _is_ a pretty large OCaml codebase if you ask me :)
=> Tezos is arguably a large OCaml code base

README.md
Adds the [Owi](https://github.com/OCamlPro/owi) and [Smt.ml](https://github.com/formalsec/smtml) projects
=> Adds Owi and Smt.ml
